// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate needs a direct (non-pooled) connection — pgbouncer's transaction
  // mode doesn't support the advisory locks / prepared statements it uses.
  // The app itself connects via the pooled DATABASE_URL (see lib/db.ts).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
