/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  mutate: [
    "lib/safeRedirect.ts",
    "lib/securityHeaders.ts",
    "lib/http/body.ts",
    "lib/http/rateLimit.ts",
    "lib/auth/credentials.ts",
    "lib/auth/rateLimit.ts",
    "lib/bookStatus.ts",
    "lib/readingStats.ts",
    "lib/apiToken.ts",
    "lib/webhook-auth.ts",
    "lib/currentUser.ts",
    "lib/auth/recoveryGrant.ts",
    "lib/supabase/auth.ts",
    "lib/supabase/session.ts",
    "lib/parsers/koreader-lua.ts",
    "lib/parsers/koreader-sqlite.ts",
    "lib/parsers/normalize.ts",
    "lib/export/toObsidianMarkdown.ts",
    "lib/ingest.ts",
    "proxy.ts",
    "app/auth/actions.ts",
    "app/auth/confirm/actions.ts",
    "app/auth/confirm/page.tsx",
    "app/login/actions.ts",
    "app/signup/actions.ts",
    "app/forgot-password/actions.ts",
    "app/reset-password/actions.ts",
    "app/reset-password/page.tsx",
    "app/api/books/*/route.ts",
    "app/api/highlights/*/route.ts",
    "app/api/export/*/route.ts",
    "app/api/upload/route.ts",
    "app/api/settings/token/route.ts",
    "app/api/webhook/cover/route.ts",
    "app/api/webhook/heartbeat/route.ts",
    "app/api/webhook/upload/route.ts",
  ],
  testRunner: "vitest",
  vitest: {
    configFile: "vitest.config.mts",
    related: true,
  },
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  coverageAnalysis: "perTest",
  concurrency: 2,
  timeoutMS: 10000,
  thresholds: {
    high: 90,
    low: 85,
    break: 85,
  },
  cleanTempDir: "always",
  reporters: ["clear-text", "progress", "html", "json"],
  htmlReporter: {
    fileName: "reports/mutation/mutation.html",
  },
  jsonReporter: {
    fileName: "reports/mutation/mutation.json",
  },
  ignorePatterns: [
    ".next",
    "coverage",
    "dist",
    "data",
    "supabase/.temp",
    "**/.env*",
  ],
};

export default config;
