-- /mnt/us/koreader/Books/[sample book].sdr/[sample book].epub.annotations.lua
return {
    ["annotations"] = {
        [1] = {
            ["chapter"] = "Chapter Two",
            ["datetime"] = "2025-12-23 04:12:04",
            ["page"] = "/body/DocFragment[22]/body/div/div/p[11]/span/text().222",
            ["pageno"] = 246,
            ["text"] = "Bookmark in chapter two",
        },
        [2] = {
            ["chapter"] = "Chapter One",
            ["color"] = "gray",
            ["datetime"] = "2026-01-02 03:09:11",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[25]/body/div/div/p[128]/span/text().160",
            ["pageno"] = 317,
            ["pos0"] = "/body/DocFragment[25]/body/div/div/p[128]/span/text().160",
            ["pos1"] = "/body/DocFragment[25]/body/div/div/p[128]/span/text().265",
            ["text"] = "A highlighted sentence with Unicode: café, 日本語, 🚀.",
        },
        [3] = {
            ["chapter"] = "Later Chapter",
            ["datetime"] = "2026-07-28 05:17:56",
            ["page"] = "/body/DocFragment[48]/body/div/div/p[67]/span/text().163",
            ["pageno"] = 715,
            ["text"] = "Bookmark in a later chapter",
        },
        [4] = {
            ["chapter"] = "Later Chapter",
            ["datetime"] = "2026-08-05 00:09:20",
            ["page"] = "/body/DocFragment[58]/body/div/div/p[120]/span[3]/text().211",
            ["pageno"] = 889,
            ["text"] = "Another bookmark in a later chapter",
        },
        [5] = {
            ["chapter"] = "Later Chapter",
            ["color"] = "gray",
            ["datetime"] = "2026-08-06 14:24:35",
            ["drawer"] = "lighten",
            ["page"] = "/body/DocFragment[62]/body/div/div/p[97]/span[2]/text().0",
            ["pageno"] = 950,
            ["pos0"] = "/body/DocFragment[62]/body/div/div/p[97]/span[2]/text().0",
            ["pos1"] = "/body/DocFragment[62]/body/div/div/p[97]/span[2]/text().236",
            ["text"] = "A second highlighted sentence",
        },
        [6] = {
            ["chapter"] = "Final Chapter",
            ["datetime"] = "2026-08-07 16:28:20",
            ["page"] = "/body/DocFragment[66]/body/div/div/p[142]/span/text().962",
            ["pageno"] = 1025,
            ["text"] = "Bookmark in the final chapter",
        },
    },
    ["cache_file_path"] = "",
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 1231,
    ["doc_path"] = "/mnt/us/koreader/Books/[sample book].epub",
    ["doc_props"] = {
        ["authors"] = "Sample Author",
        ["identifiers"] = "12341234123412",
        ["language"] = "en",
        ["title"] = "[Sample Book]",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "gray",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["invert_ui_layout"] = false,
    ["last_xpointer"] = "/body/DocFragment[68]/body/div/div/p[1].0",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "",
    ["partial_rerendering"] = true,
    ["percent_finished"] = 0.85134037367993,
    ["readermenu_tab_index"] = 8,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Sample Author",
        ["highlights"] = 2,
        ["language"] = "en",
        ["notes"] = 0,
        ["pages"] = 1231,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "[Sample Book]",
    },
    ["summary"] = {
        ["modified"] = "2025-11-22",
        ["status"] = "reading",
    },
    ["text_lang"] = "en",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
